{
    "streamer": "UP",
    "extension": "wormup",
    "game": "Wormate.io",
    "note": "Please don't copy my code",
    "programmer": "TeamUP",
    "e": "empty",
    "z": "c",
    "s11": "0.0.0.0.0.0.0.0.0.0.0",
    "sw": 1,
    "tt": 1,
    "vs": 14,
    "dsg": [],
    "propertyList": [
        {
            "id": 418,
            "type": "SKIN"
        },
        {
            "id": 400,
            "type": "EYES"
        },
        {
            "id": 400,
            "type": "MOUTH"
        }
    ],
    "cc": "<style>\n    <\/style><div id=\"div_map\"><\/div><p id=\"update_new_2\" style=\"text-align: center;position: absolute;bottom: -15px;width: 100%;background-image: linear-gradient(#ffffff, #ffffff);font-weight: bold;color: black;border: 1px solid;border-radius: 10px;border-color: #ffffff;\">من فضلك ، امسح سجل المتصفح لتحديث الاضافة. شكرًا.<\/p>",
    "mb": "<div class='info-message' style='background-color: rgba(255, 204, 0, 0.1); border-radius: 8px; padding: 15px; margin: 10px 0; border: 1px solid rgba(255, 204, 0, 0.3);'><h4 class='center' style='color: #ffbb00; margin-top: 0;'>ملاحظة مهمة<\/h4><p style='text-align: right; direction: rtl; margin-bottom: 10px;'>يمكنك زيادة سرعة الزوم والتصغير من خلال زيارة قسم \"حجم الادوات والزوم\" وضبط شريط تمرير سرعة الزوم للحصول على تجربة لعب أفضل.<\/p><p style='text-align: left; direction: ltr; margin-bottom: 0;'>You can increase the zoom speed by visiting the \"Power-ups & Zoom\" section and adjusting the zoom speed slider for a better gaming experience.<\/p><\/div>",
    "cm": "",
    "cr": "",
    "ccc": "iq",
    "ccg": [
        "Will Kill and Headshot statistics be removed?",
        "There was a connection problem!",
        "Your account has been locked.",
        "RESPAWN",
        "Full Screen",
        "In the game",
        "⚙️ Settings",
        "ID",
        "ID COPY",
        "COPY ID",
        "Country",
        "Remember kill and headshot counts",
        "ON\/OFF",
        "Background image",
        "COPY",
        "Vietnam",
        "Thailand",
        "Cambodia",
        "Indonesia",
        "Singapore",
        "Japan",
        "Mexico",
        "Brazil",
        "Canada",
        "Germany",
        "France",
        "England",
        "Australia",
        "USA",
        "Portugal",
        "Shortcut",
        "Dark blue sky",
        "Purple sky",
        "Clouds",
        "💡",
        "Turkey",
        "Arabs"
    ],
    "is_subscriber": false,
    "show_discord": true,
    "discord_button": "\n<div id=\"discord-link-container\" style=\"margin-top: 20px; text-align: center;\">\n  <a href=\"https:\/\/discord.gg\/your-discord-link\" target=\"_blank\" style=\"display: inline-block; background-color: #5865F2; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px; font-weight: bold;\">\n    <img src=\"https:\/\/assets-global.website-files.com\/6257adef93867e50d84d30e2\/636e0a6a49cf127bf92de1e2_icon_clyde_white_RGB.png\" alt=\"Discord\" style=\"height: 20px; vertical-align: middle; margin-right: 8px;\">\n    انضم إلى مجتمعنا على Discord\n  <\/a>\n  <p style=\"margin-top: 10px; font-size: 13px; color: #666;\">للحصول على ميزات إضافية، انضم إلى سيرفر Discord واشترك في النسخة المميزة<\/p>\n<\/div>\n",
    "server_time": "2025-05-10 15:10:23"
}
